default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: concon_development

test:
  <<: *default
  database: concon_test

production:
  <<: *default
  database: concon_production
